project:
  type: website
  render:
    - "*.qmd"
    - "!exercises/"
  resources: 
    - "exercises/"

website:
  page-navigation: true
  title: "Intro to Quarto"
  description: "Intro to Quarto Cascadia R Conf Workshop 2024"
  repo-url: https://github.com/cwickham/quarto-workshop-website
  page-footer:
    center:
      - icon: github
        href: https://github.com/cwickham/quarto-workshop-website
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
  open-graph: true
  sidebar:
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: pre-work.qmd
        text: Pre-work
      - text: "---"
      - section: Modules
        contents:
        - href: 1-hello-quarto/index.qmd
          text: Hello Quarto
        - href: 2-yaml-markdown-basics/index.qmd
          text: YAML + Markdown Basics
        - href: 3-figures-tables-code/index.qmd
          text: Figures/Tables + Code
        - href: 4-wrap-up/index.qmd
          text: Wrap Up
    
format:
  html:
    theme: 
      light: style/quarto-asa-light.scss
      dark: style/quarto-asa-dark.scss
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    toc: false
  revealjs:
    footer: "[charlotte.quarto.pub/cascadia](https://charlotte.quarto.pub/cascadia)"
    author: Charlotte Wickham
    institute: Posit, PBC
    transition: fade
    slide-number: true
    chalkboard: false
    theme: style/slides.scss

execute:
  freeze: auto
  echo: true